services:
  app:
    image: "${APP_IMAGE}"
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - SERVICE_GATEWAY_URL=http://specmatic:9000
    depends_on:
      specmatic:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "${APP_HEALTH_ENDPOINT}"]
      timeout: 2s
      retries: 20
      start_period: 1s

  specmatic:
    image: "${SPECMATIC_IMAGE}"
    ports:
      - "${SPECMATIC_PORT:-9000}:9000"
    volumes:
      - ./:/app
    command: stub
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      timeout: 2s
      retries: 20
      start_period: 1s
